// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAlbumPhotoCount = `-- name: AddAlbumPhotoCount :exec
UPDATE albums
SET photo_count = photo_count + $2, updated_at = now()
WHERE id = $1
`

type AddAlbumPhotoCountParams struct {
	ID         uuid.UUID `json:"id"`
	PhotoCount int32     `json:"photo_count"`
}

func (q *Queries) AddAlbumPhotoCount(ctx context.Context, arg AddAlbumPhotoCountParams) error {
	_, err := q.db.Exec(ctx, addAlbumPhotoCount, arg.ID, arg.PhotoCount)
	return err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (shop_id, parent_id, title, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id
`

type CreateAlbumParams struct {
	ShopID    uuid.UUID     `json:"shop_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Title     string        `json:"title"`
	SortOrder int32         `json:"sort_order"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ShopID,
		arg.ParentID,
		arg.Title,
		arg.SortOrder,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.IsHidden,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :execrows
DELETE FROM albums
WHERE id = $1 AND shop_id = $2
`

type DeleteAlbumParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteAlbum(ctx context.Context, arg DeleteAlbumParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlbum, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlbumForShop = `-- name: GetAlbumForShop :one
SELECT id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id FROM albums
WHERE id = $1 AND shop_id = $2
`

type GetAlbumForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к альбому только в связке с shop_id владельца.
func (q *Queries) GetAlbumForShop(ctx context.Context, arg GetAlbumForShopParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumForShop, arg.ID, arg.ShopID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.IsHidden,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const listAlbumsByShop = `-- name: ListAlbumsByShop :many
SELECT id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id FROM albums
WHERE shop_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListAlbumsByShop(ctx context.Context, shopID uuid.UUID) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.CoverPhotoID,
			&i.SortOrder,
			&i.IsHidden,
			&i.PasswordHash,
			&i.PhotoCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET title          = $3,
    sort_order     = $4,
    is_hidden      = $5,
    cover_photo_id = $6,
    updated_at     = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id
`

type UpdateAlbumParams struct {
	ID           uuid.UUID     `json:"id"`
	ShopID       uuid.UUID     `json:"shop_id"`
	Title        string        `json:"title"`
	SortOrder    int32         `json:"sort_order"`
	IsHidden     bool          `json:"is_hidden"`
	CoverPhotoID uuid.NullUUID `json:"cover_photo_id"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.ShopID,
		arg.Title,
		arg.SortOrder,
		arg.IsHidden,
		arg.CoverPhotoID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.IsHidden,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}
