// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAlbumPhotoCount = `-- name: AddAlbumPhotoCount :exec
UPDATE albums
SET photo_count = photo_count + $2, updated_at = now()
WHERE id = $1
`

type AddAlbumPhotoCountParams struct {
	ID         uuid.UUID `json:"id"`
	PhotoCount int32     `json:"photo_count"`
}

func (q *Queries) AddAlbumPhotoCount(ctx context.Context, arg AddAlbumPhotoCountParams) error {
	_, err := q.db.Exec(ctx, addAlbumPhotoCount, arg.ID, arg.PhotoCount)
	return err
}

const applyPlanVisibility = `-- name: ApplyPlanVisibility :exec
UPDATE albums
SET hidden_by_plan = NOT (id = ANY($2::uuid[])),
    updated_at     = now()
WHERE shop_id = $1
`

type ApplyPlanVisibilityParams struct {
	ShopID  uuid.UUID   `json:"shop_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

// Применение выбора: видимыми остаются только перечисленные альбомы.
// Ничего не удаляется — снимается лишь видимость на витрине.
func (q *Queries) ApplyPlanVisibility(ctx context.Context, arg ApplyPlanVisibilityParams) error {
	_, err := q.db.Exec(ctx, applyPlanVisibility, arg.ShopID, arg.Column2)
	return err
}

const clearPlanVisibility = `-- name: ClearPlanVisibility :execrows
UPDATE albums
SET hidden_by_plan = false, updated_at = now()
WHERE shop_id = $1 AND hidden_by_plan
`

// Возврат после оплаты: скрытое тарифом возвращается целиком и сразу.
func (q *Queries) ClearPlanVisibility(ctx context.Context, shopID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearPlanVisibility, shopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAlbumsByShop = `-- name: CountAlbumsByShop :one
SELECT count(*) FROM albums WHERE shop_id = $1
`

func (q *Queries) CountAlbumsByShop(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumsByShop, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (shop_id, parent_id, title, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, password_hash, photo_count, created_at, updated_at, category_id, status, hidden_by_plan, description, blocked_by_moderator
`

type CreateAlbumParams struct {
	ShopID    uuid.UUID     `json:"shop_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Title     string        `json:"title"`
	SortOrder int32         `json:"sort_order"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ShopID,
		arg.ParentID,
		arg.Title,
		arg.SortOrder,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Status,
		&i.HiddenByPlan,
		&i.Description,
		&i.BlockedByModerator,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :execrows
DELETE FROM albums
WHERE id = $1 AND shop_id = $2
`

type DeleteAlbumParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteAlbum(ctx context.Context, arg DeleteAlbumParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlbum, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlbumForShop = `-- name: GetAlbumForShop :one
SELECT id, shop_id, parent_id, title, cover_photo_id, sort_order, password_hash, photo_count, created_at, updated_at, category_id, status, hidden_by_plan, description, blocked_by_moderator FROM albums
WHERE id = $1 AND shop_id = $2
`

type GetAlbumForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к альбому только в связке с shop_id владельца.
func (q *Queries) GetAlbumForShop(ctx context.Context, arg GetAlbumForShopParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumForShop, arg.ID, arg.ShopID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Status,
		&i.HiddenByPlan,
		&i.Description,
		&i.BlockedByModerator,
	)
	return i, err
}

const listAlbumsByShop = `-- name: ListAlbumsByShop :many
SELECT id, shop_id, parent_id, title, cover_photo_id, sort_order, password_hash, photo_count, created_at, updated_at, category_id, status, hidden_by_plan, description, blocked_by_moderator FROM albums
WHERE shop_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListAlbumsByShop(ctx context.Context, shopID uuid.UUID) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.CoverPhotoID,
			&i.SortOrder,
			&i.PasswordHash,
			&i.PhotoCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.Status,
			&i.HiddenByPlan,
			&i.Description,
			&i.BlockedByModerator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsForDowngrade = `-- name: ListAlbumsForDowngrade :many
SELECT a.id, a.title, a.photo_count, a.hidden_by_plan, a.created_at,
       coalesce(sum(d.views), 0)::bigint AS views
FROM albums a
LEFT JOIN daily_stats d
       ON d.album_id = a.id AND d.date >= (current_date - 30)
WHERE a.shop_id = $1
GROUP BY a.id
ORDER BY views DESC, a.created_at DESC
`

type ListAlbumsForDowngradeRow struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	PhotoCount   int32              `json:"photo_count"`
	HiddenByPlan bool               `json:"hidden_by_plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Views        int64              `json:"views"`
}

// Экран понижения тарифа: альбомы с числом фото и просмотрами за 30 дней.
// Просмотры нужны для варианта «самые просматриваемые» — он предзаполнен,
// потому что чаще всего это и есть правильный выбор.
func (q *Queries) ListAlbumsForDowngrade(ctx context.Context, shopID uuid.UUID) ([]ListAlbumsForDowngradeRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsForDowngrade, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsForDowngradeRow
	for rows.Next() {
		var i ListAlbumsForDowngradeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PhotoCount,
			&i.HiddenByPlan,
			&i.CreatedAt,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET title          = $3,
    sort_order     = $4,
    status         = $5,
    cover_photo_id = $6,
    description    = $7,
    updated_at     = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, password_hash, photo_count, created_at, updated_at, category_id, status, hidden_by_plan, description, blocked_by_moderator
`

type UpdateAlbumParams struct {
	ID           uuid.UUID     `json:"id"`
	ShopID       uuid.UUID     `json:"shop_id"`
	Title        string        `json:"title"`
	SortOrder    int32         `json:"sort_order"`
	Status       AlbumStatus   `json:"status"`
	CoverPhotoID uuid.NullUUID `json:"cover_photo_id"`
	Description  string        `json:"description"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.ID,
		arg.ShopID,
		arg.Title,
		arg.SortOrder,
		arg.Status,
		arg.CoverPhotoID,
		arg.Description,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Status,
		&i.HiddenByPlan,
		&i.Description,
		&i.BlockedByModerator,
	)
	return i, err
}
