// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :execrows
UPDATE subscriptions
SET status = 'canceled', updated_at = now()
WHERE shop_id = $1 AND status = 'active'
`

// Отмена автопродления: подписка живёт до конца оплаченного периода.
func (q *Queries) CancelSubscription(ctx context.Context, shopID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSubscription, shopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countShopPhotos = `-- name: CountShopPhotos :one
SELECT count(*) FROM photos
WHERE shop_id = $1 AND status != 'failed'
`

// Лимит фото тарифа: слот занимают все фото, кроме failed.
func (q *Queries) CountShopPhotos(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countShopPhotos, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (shop_id, plan, amount, currency, recurring)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shop_id, plan, amount, currency, provider_payment_id, status, recurring, created_at, updated_at
`

type CreatePaymentParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	Plan      ShopPlan  `json:"plan"`
	Amount    int64     `json:"amount"`
	Currency  string    `json:"currency"`
	Recurring bool      `json:"recurring"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ShopID,
		arg.Plan,
		arg.Amount,
		arg.Currency,
		arg.Recurring,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Plan,
		&i.Amount,
		&i.Currency,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Recurring,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderID = `-- name: GetPaymentByProviderID :one
SELECT id, shop_id, plan, amount, currency, provider_payment_id, status, recurring, created_at, updated_at FROM payments
WHERE provider_payment_id = $1
`

func (q *Queries) GetPaymentByProviderID(ctx context.Context, providerPaymentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Plan,
		&i.Amount,
		&i.Currency,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Recurring,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByShop = `-- name: GetSubscriptionByShop :one

SELECT id, shop_id, plan, status, period_start, period_end, created_at, payment_method_id, updated_at FROM subscriptions
WHERE shop_id = $1
`

// Подписки, платежи ЮKassa и биллинговый жизненный цикл магазинов.
func (q *Queries) GetSubscriptionByShop(ctx context.Context, shopID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByShop, shopID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Plan,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.PaymentMethodID,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsToRenew = `-- name: ListSubscriptionsToRenew :many
SELECT s.id, s.shop_id, s.plan, s.status, s.period_start, s.period_end, s.created_at, s.payment_method_id, s.updated_at FROM subscriptions s
WHERE s.status = 'active'
  AND s.payment_method_id IS NOT NULL
  AND s.period_end < now() + interval '1 day'
  AND NOT EXISTS (
      SELECT 1 FROM payments p
      WHERE p.shop_id = s.shop_id AND p.recurring AND p.status = 'pending'
  )
`

// Рекуррентные списания: активные подписки с сохранённым способом оплаты,
// истекающие в ближайшие сутки, без незавершённого рекуррентного платежа.
func (q *Queries) ListSubscriptionsToRenew(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsToRenew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Plan,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CreatedAt,
			&i.PaymentMethodID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionsExpired = `-- name: MarkSubscriptionsExpired :exec
UPDATE subscriptions s
SET status = 'expired', updated_at = now()
FROM shops sh
WHERE s.shop_id = sh.id AND sh.billing_state = 'suspended'
  AND s.status IN ('active', 'past_due', 'canceled')
`

func (q *Queries) MarkSubscriptionsExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSubscriptionsExpired)
	return err
}

const markSubscriptionsPastDue = `-- name: MarkSubscriptionsPastDue :exec
UPDATE subscriptions s
SET status = 'past_due', updated_at = now()
FROM shops sh
WHERE s.shop_id = sh.id AND sh.billing_state = 'grace' AND s.status = 'active'
`

func (q *Queries) MarkSubscriptionsPastDue(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSubscriptionsPastDue)
	return err
}

const setPaymentProvider = `-- name: SetPaymentProvider :exec
UPDATE payments
SET provider_payment_id = $2, updated_at = now()
WHERE id = $1
`

type SetPaymentProviderParams struct {
	ID                uuid.UUID `json:"id"`
	ProviderPaymentID *string   `json:"provider_payment_id"`
}

func (q *Queries) SetPaymentProvider(ctx context.Context, arg SetPaymentProviderParams) error {
	_, err := q.db.Exec(ctx, setPaymentProvider, arg.ID, arg.ProviderPaymentID)
	return err
}

const setPaymentStatus = `-- name: SetPaymentStatus :exec
UPDATE payments
SET status = $2, updated_at = now()
WHERE id = $1
`

type SetPaymentStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status PaymentStatus `json:"status"`
}

func (q *Queries) SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, setPaymentStatus, arg.ID, arg.Status)
	return err
}

const setShopPaid = `-- name: SetShopPaid :exec
UPDATE shops
SET plan = $2, billing_state = 'ok', paid_until = $3, updated_at = now()
WHERE id = $1
`

type SetShopPaidParams struct {
	ID        uuid.UUID          `json:"id"`
	Plan      ShopPlan           `json:"plan"`
	PaidUntil pgtype.Timestamptz `json:"paid_until"`
}

func (q *Queries) SetShopPaid(ctx context.Context, arg SetShopPaidParams) error {
	_, err := q.db.Exec(ctx, setShopPaid, arg.ID, arg.Plan, arg.PaidUntil)
	return err
}

const settlePayment = `-- name: SettlePayment :one
UPDATE payments
SET status = $2, updated_at = now()
WHERE provider_payment_id = $1 AND status = 'pending'
RETURNING id, shop_id, plan, amount, currency, provider_payment_id, status, recurring, created_at, updated_at
`

type SettlePaymentParams struct {
	ProviderPaymentID *string       `json:"provider_payment_id"`
	Status            PaymentStatus `json:"status"`
}

// Идемпотентность вебхука: перевод из pending срабатывает ровно один раз,
// повторная доставка события не находит строку и становится no-op.
func (q *Queries) SettlePayment(ctx context.Context, arg SettlePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, settlePayment, arg.ProviderPaymentID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Plan,
		&i.Amount,
		&i.Currency,
		&i.ProviderPaymentID,
		&i.Status,
		&i.Recurring,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shopsEnterGrace = `-- name: ShopsEnterGrace :many
UPDATE shops
SET billing_state = 'grace', updated_at = now()
WHERE plan != 'free' AND billing_state = 'ok'
  AND paid_until IS NOT NULL AND paid_until < now()
RETURNING id, slug
`

type ShopsEnterGraceRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// Жизненный цикл: оплата истекла -> grace (загрузка заблокирована).
func (q *Queries) ShopsEnterGrace(ctx context.Context) ([]ShopsEnterGraceRow, error) {
	rows, err := q.db.Query(ctx, shopsEnterGrace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopsEnterGraceRow
	for rows.Next() {
		var i ShopsEnterGraceRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shopsEnterSuspended = `-- name: ShopsEnterSuspended :many
UPDATE shops
SET billing_state = 'suspended', updated_at = now()
WHERE plan != 'free' AND billing_state = 'grace'
  AND paid_until < now() - make_interval(days => $1)
RETURNING id, slug
`

type ShopsEnterSuspendedRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// Grace истёк -> suspended (витрина скрыта, контент не удаляется).
func (q *Queries) ShopsEnterSuspended(ctx context.Context, days int32) ([]ShopsEnterSuspendedRow, error) {
	rows, err := q.db.Query(ctx, shopsEnterSuspended, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopsEnterSuspendedRow
	for rows.Next() {
		var i ShopsEnterSuspendedRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscriptionPaid = `-- name: UpsertSubscriptionPaid :one
INSERT INTO subscriptions (shop_id, plan, status, period_start, period_end, payment_method_id)
VALUES ($1, $2, 'active', now(), now() + make_interval(days => $3), $4)
ON CONFLICT (shop_id) DO UPDATE SET
    plan              = EXCLUDED.plan,
    status            = 'active',
    period_end        = greatest(subscriptions.period_end, now()) + make_interval(days => $3),
    payment_method_id = coalesce(EXCLUDED.payment_method_id, subscriptions.payment_method_id),
    updated_at        = now()
RETURNING id, shop_id, plan, status, period_start, period_end, created_at, payment_method_id, updated_at
`

type UpsertSubscriptionPaidParams struct {
	ShopID          uuid.UUID `json:"shop_id"`
	Plan            ShopPlan  `json:"plan"`
	Days            int32     `json:"days"`
	PaymentMethodID *string   `json:"payment_method_id"`
}

// Успешная оплата: создать подписку или продлить существующую.
// Период продлевается от текущего конца, если он в будущем, иначе от now().
func (q *Queries) UpsertSubscriptionPaid(ctx context.Context, arg UpsertSubscriptionPaidParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscriptionPaid,
		arg.ShopID,
		arg.Plan,
		arg.Days,
		arg.PaymentMethodID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Plan,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CreatedAt,
		&i.PaymentMethodID,
		&i.UpdatedAt,
	)
	return i, err
}
