// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (shop_id, parent_id, title, slug, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shop_id, parent_id, title, slug, sort_order, created_at, updated_at
`

type CreateCategoryParams struct {
	ShopID    uuid.UUID     `json:"shop_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Title     string        `json:"title"`
	Slug      string        `json:"slug"`
	SortOrder int32         `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ShopID,
		arg.ParentID,
		arg.Title,
		arg.Slug,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = $1 AND shop_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryForShop = `-- name: GetCategoryForShop :one
SELECT id, shop_id, parent_id, title, slug, sort_order, created_at, updated_at FROM categories
WHERE id = $1 AND shop_id = $2
`

type GetCategoryForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к категории только в связке с shop_id владельца.
func (q *Queries) GetCategoryForShop(ctx context.Context, arg GetCategoryForShopParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryForShop, arg.ID, arg.ShopID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByShop = `-- name: ListCategoriesByShop :many
SELECT id, shop_id, parent_id, title, slug, sort_order, created_at, updated_at FROM categories
WHERE shop_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListCategoriesByShop(ctx context.Context, shopID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicAlbumsByCategory = `-- name: ListPublicAlbumsByCategory :many
SELECT a.id, a.shop_id, a.parent_id, a.title, a.cover_photo_id, a.sort_order, a.is_hidden, a.password_hash, a.photo_count, a.created_at, a.updated_at, a.category_id FROM albums a
JOIN categories c ON c.id = a.category_id
WHERE a.shop_id = $1
  AND a.is_hidden = false
  AND (c.slug = $2 OR c.parent_id = (SELECT id FROM categories WHERE shop_id = $1 AND slug = $2))
ORDER BY a.sort_order, a.created_at DESC
`

type ListPublicAlbumsByCategoryParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) ListPublicAlbumsByCategory(ctx context.Context, arg ListPublicAlbumsByCategoryParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listPublicAlbumsByCategory, arg.ShopID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.CoverPhotoID,
			&i.SortOrder,
			&i.IsHidden,
			&i.PasswordHash,
			&i.PhotoCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCategories = `-- name: ListPublicCategories :many
SELECT c.id, c.shop_id, c.parent_id, c.title, c.slug, c.sort_order, c.created_at, c.updated_at, count(a.id) FILTER (WHERE a.is_hidden = false) AS album_count
FROM categories c
LEFT JOIN albums a ON a.category_id = c.id
WHERE c.shop_id = $1
GROUP BY c.id
ORDER BY c.sort_order, c.created_at
`

type ListPublicCategoriesRow struct {
	ID         uuid.UUID          `json:"id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	ParentID   uuid.NullUUID      `json:"parent_id"`
	Title      string             `json:"title"`
	Slug       string             `json:"slug"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AlbumCount int64              `json:"album_count"`
}

// Публичное дерево категорий витрины: только те, где есть видимые альбомы,
// либо есть потомок с видимыми. Горячий путь покупателя — один запрос.
func (q *Queries) ListPublicCategories(ctx context.Context, shopID uuid.UUID) ([]ListPublicCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicCategories, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicCategoriesRow
	for rows.Next() {
		var i ListPublicCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AlbumCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAlbumsToCategory = `-- name: MoveAlbumsToCategory :exec
UPDATE albums
SET category_id = $3, updated_at = now()
WHERE shop_id = $1 AND category_id = $2
`

type MoveAlbumsToCategoryParams struct {
	ShopID       uuid.UUID     `json:"shop_id"`
	CategoryID   uuid.NullUUID `json:"category_id"`
	CategoryID_2 uuid.NullUUID `json:"category_id_2"`
}

// Перенос альбомов при удалении категории: продавец выбирает целевую
// (NULL = оставить без категории). Ограничение по shop_id — на случай
// подставленного чужого id.
func (q *Queries) MoveAlbumsToCategory(ctx context.Context, arg MoveAlbumsToCategoryParams) error {
	_, err := q.db.Exec(ctx, moveAlbumsToCategory, arg.ShopID, arg.CategoryID, arg.CategoryID_2)
	return err
}

const setAlbumCategory = `-- name: SetAlbumCategory :one
UPDATE albums
SET category_id = $3, updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id
`

type SetAlbumCategoryParams struct {
	ID         uuid.UUID     `json:"id"`
	ShopID     uuid.UUID     `json:"shop_id"`
	CategoryID uuid.NullUUID `json:"category_id"`
}

func (q *Queries) SetAlbumCategory(ctx context.Context, arg SetAlbumCategoryParams) (Album, error) {
	row := q.db.QueryRow(ctx, setAlbumCategory, arg.ID, arg.ShopID, arg.CategoryID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.IsHidden,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET title      = $3,
    slug       = $4,
    sort_order = $5,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, parent_id, title, slug, sort_order, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Title     string    `json:"title"`
	Slug      string    `json:"slug"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.ShopID,
		arg.Title,
		arg.Slug,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.Slug,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
