// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminBlockPhoto = `-- name: AdminBlockPhoto :one
UPDATE photos
SET status = 'blocked', updated_at = now()
WHERE id = $1 AND status != 'blocked'
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged
`

// Блокировка фото модератором: исчезает с витрины (status фильтруется
// везде по 'ready'), деривативы удаляются из S3 в handler. Оригинал остаётся.
func (q *Queries) AdminBlockPhoto(ctx context.Context, id uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, adminBlockPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}

const adminHideAlbum = `-- name: AdminHideAlbum :one
UPDATE albums
SET is_hidden = true, updated_at = now()
WHERE id = $1
RETURNING id, shop_id, parent_id, title, cover_photo_id, sort_order, is_hidden, password_hash, photo_count, created_at, updated_at, category_id
`

func (q *Queries) AdminHideAlbum(ctx context.Context, id uuid.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, adminHideAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.IsHidden,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
	)
	return i, err
}

const adminSuspendShop = `-- name: AdminSuspendShop :one
UPDATE shops
SET status = 'suspended', updated_at = now()
WHERE id = $1
RETURNING id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until
`

func (q *Queries) AdminSuspendShop(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, adminSuspendShop, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
	)
	return i, err
}

const createComplaint = `-- name: CreateComplaint :one

INSERT INTO complaints (shop_id, photo_id, reason, reporter_name, reporter_email, content_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, shop_id, photo_id, reason, status, created_at, resolved_at, reporter_name, reporter_email, content_url
`

type CreateComplaintParams struct {
	ShopID        uuid.NullUUID `json:"shop_id"`
	PhotoID       uuid.NullUUID `json:"photo_id"`
	Reason        string        `json:"reason"`
	ReporterName  string        `json:"reporter_name"`
	ReporterEmail string        `json:"reporter_email"`
	ContentUrl    string        `json:"content_url"`
}

// Жалобы правообладателей (notice-and-takedown) и действия модератора.
func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, createComplaint,
		arg.ShopID,
		arg.PhotoID,
		arg.Reason,
		arg.ReporterName,
		arg.ReporterEmail,
		arg.ContentUrl,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.PhotoID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.ContentUrl,
	)
	return i, err
}

const createModerationLog = `-- name: CreateModerationLog :one
INSERT INTO moderation_log (admin_id, action, complaint_id, shop_id, album_id, photo_id, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, admin_id, action, complaint_id, shop_id, album_id, photo_id, note, created_at
`

type CreateModerationLogParams struct {
	AdminID     uuid.UUID        `json:"admin_id"`
	Action      ModerationAction `json:"action"`
	ComplaintID uuid.NullUUID    `json:"complaint_id"`
	ShopID      uuid.NullUUID    `json:"shop_id"`
	AlbumID     uuid.NullUUID    `json:"album_id"`
	PhotoID     uuid.NullUUID    `json:"photo_id"`
	Note        string           `json:"note"`
}

func (q *Queries) CreateModerationLog(ctx context.Context, arg CreateModerationLogParams) (ModerationLog, error) {
	row := q.db.QueryRow(ctx, createModerationLog,
		arg.AdminID,
		arg.Action,
		arg.ComplaintID,
		arg.ShopID,
		arg.AlbumID,
		arg.PhotoID,
		arg.Note,
	)
	var i ModerationLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.ComplaintID,
		&i.ShopID,
		&i.AlbumID,
		&i.PhotoID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getComplaint = `-- name: GetComplaint :one
SELECT id, shop_id, photo_id, reason, status, created_at, resolved_at, reporter_name, reporter_email, content_url FROM complaints
WHERE id = $1
`

func (q *Queries) GetComplaint(ctx context.Context, id uuid.UUID) (Complaint, error) {
	row := q.db.QueryRow(ctx, getComplaint, id)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.PhotoID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.ContentUrl,
	)
	return i, err
}

const getShopBySlugAny = `-- name: GetShopBySlugAny :one
SELECT id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until FROM shops
WHERE slug = $1
`

// Для резолва жалобы по URL: магазин по slug независимо от статуса.
func (q *Queries) GetShopBySlugAny(ctx context.Context, slug string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopBySlugAny, slug)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
	)
	return i, err
}

const listComplaints = `-- name: ListComplaints :many
SELECT c.id, c.shop_id, c.photo_id, c.reason, c.status, c.created_at, c.resolved_at, c.reporter_name, c.reporter_email, c.content_url, s.slug AS shop_slug, p.album_id AS photo_album_id
FROM complaints c
LEFT JOIN shops s ON s.id = c.shop_id
LEFT JOIN photos p ON p.id = c.photo_id
WHERE $1::complaint_status IS NULL OR c.status = $1
ORDER BY c.created_at DESC
LIMIT 200
`

type ListComplaintsRow struct {
	ID            uuid.UUID          `json:"id"`
	ShopID        uuid.NullUUID      `json:"shop_id"`
	PhotoID       uuid.NullUUID      `json:"photo_id"`
	Reason        string             `json:"reason"`
	Status        ComplaintStatus    `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	ReporterName  string             `json:"reporter_name"`
	ReporterEmail string             `json:"reporter_email"`
	ContentUrl    string             `json:"content_url"`
	ShopSlug      *string            `json:"shop_slug"`
	PhotoAlbumID  uuid.NullUUID      `json:"photo_album_id"`
}

// Список для админ-зоны: с slug магазина и альбомом фото (для действий).
func (q *Queries) ListComplaints(ctx context.Context, status NullComplaintStatus) ([]ListComplaintsRow, error) {
	rows, err := q.db.Query(ctx, listComplaints, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComplaintsRow
	for rows.Next() {
		var i ListComplaintsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.PhotoID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.ContentUrl,
			&i.ShopSlug,
			&i.PhotoAlbumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlaggedPhotos = `-- name: ListFlaggedPhotos :many
SELECT p.id, p.album_id, p.shop_id, p.caption, p.caption_tsv, p.status, p.orig_size, p.width, p.height, p.phash, p.source, p.sort_order, p.created_at, p.updated_at, p.flagged, s.slug AS shop_slug
FROM photos p
JOIN shops s ON s.id = p.shop_id
WHERE p.flagged
ORDER BY p.updated_at DESC
LIMIT 200
`

type ListFlaggedPhotosRow struct {
	ID         uuid.UUID          `json:"id"`
	AlbumID    uuid.UUID          `json:"album_id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	Caption    string             `json:"caption"`
	CaptionTsv interface{}        `json:"caption_tsv"`
	Status     PhotoStatus        `json:"status"`
	OrigSize   int64              `json:"orig_size"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Phash      pgtype.Int8        `json:"phash"`
	Source     PhotoSource        `json:"source"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Flagged    bool               `json:"flagged"`
	ShopSlug   string             `json:"shop_slug"`
}

func (q *Queries) ListFlaggedPhotos(ctx context.Context) ([]ListFlaggedPhotosRow, error) {
	rows, err := q.db.Query(ctx, listFlaggedPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlaggedPhotosRow
	for rows.Next() {
		var i ListFlaggedPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.ShopSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setComplaintStatus = `-- name: SetComplaintStatus :one
UPDATE complaints
SET status      = $2,
    resolved_at = CASE WHEN $2::complaint_status IN ('resolved', 'rejected')
                       THEN now() ELSE resolved_at END
WHERE id = $1
RETURNING id, shop_id, photo_id, reason, status, created_at, resolved_at, reporter_name, reporter_email, content_url
`

type SetComplaintStatusParams struct {
	ID     uuid.UUID       `json:"id"`
	Status ComplaintStatus `json:"status"`
}

func (q *Queries) SetComplaintStatus(ctx context.Context, arg SetComplaintStatusParams) (Complaint, error) {
	row := q.db.QueryRow(ctx, setComplaintStatus, arg.ID, arg.Status)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.PhotoID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ReporterName,
		&i.ReporterEmail,
		&i.ContentUrl,
	)
	return i, err
}

const setPhotoFlagged = `-- name: SetPhotoFlagged :exec
UPDATE photos
SET flagged = $2, updated_at = now()
WHERE id = $1
`

type SetPhotoFlaggedParams struct {
	ID      uuid.UUID `json:"id"`
	Flagged bool      `json:"flagged"`
}

func (q *Queries) SetPhotoFlagged(ctx context.Context, arg SetPhotoFlaggedParams) error {
	_, err := q.db.Exec(ctx, setPhotoFlagged, arg.ID, arg.Flagged)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}
