// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingState string

const (
	BillingStateOk        BillingState = "ok"
	BillingStateGrace     BillingState = "grace"
	BillingStateSuspended BillingState = "suspended"
)

func (e *BillingState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingState(s)
	case string:
		*e = BillingState(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingState: %T", src)
	}
	return nil
}

type NullBillingState struct {
	BillingState BillingState `json:"billing_state"`
	Valid        bool         `json:"valid"` // Valid is true if BillingState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingState) Scan(value interface{}) error {
	if value == nil {
		ns.BillingState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingState), nil
}

type ComplaintStatus string

const (
	ComplaintStatusOpen     ComplaintStatus = "open"
	ComplaintStatusInReview ComplaintStatus = "in_review"
	ComplaintStatusResolved ComplaintStatus = "resolved"
	ComplaintStatusRejected ComplaintStatus = "rejected"
)

func (e *ComplaintStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintStatus(s)
	case string:
		*e = ComplaintStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintStatus: %T", src)
	}
	return nil
}

type NullComplaintStatus struct {
	ComplaintStatus ComplaintStatus `json:"complaint_status"`
	Valid           bool            `json:"valid"` // Valid is true if ComplaintStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintStatus), nil
}

type LeadChannel string

const (
	LeadChannelTelegram LeadChannel = "telegram"
	LeadChannelWhatsapp LeadChannel = "whatsapp"
	LeadChannelMax      LeadChannel = "max"
	LeadChannelVk       LeadChannel = "vk"
)

func (e *LeadChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadChannel(s)
	case string:
		*e = LeadChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadChannel: %T", src)
	}
	return nil
}

type NullLeadChannel struct {
	LeadChannel LeadChannel `json:"lead_channel"`
	Valid       bool        `json:"valid"` // Valid is true if LeadChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadChannel) Scan(value interface{}) error {
	if value == nil {
		ns.LeadChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadChannel), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusSucceeded PaymentStatus = "succeeded"
	PaymentStatusCanceled  PaymentStatus = "canceled"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PhotoSource string

const (
	PhotoSourceUpload PhotoSource = "upload"
	PhotoSourceImport PhotoSource = "import"
)

func (e *PhotoSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoSource(s)
	case string:
		*e = PhotoSource(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoSource: %T", src)
	}
	return nil
}

type NullPhotoSource struct {
	PhotoSource PhotoSource `json:"photo_source"`
	Valid       bool        `json:"valid"` // Valid is true if PhotoSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoSource) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoSource), nil
}

type PhotoStatus string

const (
	PhotoStatusUploading  PhotoStatus = "uploading"
	PhotoStatusProcessing PhotoStatus = "processing"
	PhotoStatusReady      PhotoStatus = "ready"
	PhotoStatusFailed     PhotoStatus = "failed"
	PhotoStatusBlocked    PhotoStatus = "blocked"
)

func (e *PhotoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoStatus(s)
	case string:
		*e = PhotoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoStatus: %T", src)
	}
	return nil
}

type NullPhotoStatus struct {
	PhotoStatus PhotoStatus `json:"photo_status"`
	Valid       bool        `json:"valid"` // Valid is true if PhotoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoStatus), nil
}

type ShopPlan string

const (
	ShopPlanFree  ShopPlan = "free"
	ShopPlanBasic ShopPlan = "basic"
	ShopPlanPro   ShopPlan = "pro"
)

func (e *ShopPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopPlan(s)
	case string:
		*e = ShopPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopPlan: %T", src)
	}
	return nil
}

type NullShopPlan struct {
	ShopPlan ShopPlan `json:"shop_plan"`
	Valid    bool     `json:"valid"` // Valid is true if ShopPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopPlan) Scan(value interface{}) error {
	if value == nil {
		ns.ShopPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopPlan), nil
}

type ShopStatus string

const (
	ShopStatusActive    ShopStatus = "active"
	ShopStatusSuspended ShopStatus = "suspended"
	ShopStatusDeleted   ShopStatus = "deleted"
)

func (e *ShopStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopStatus(s)
	case string:
		*e = ShopStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopStatus: %T", src)
	}
	return nil
}

type NullShopStatus struct {
	ShopStatus ShopStatus `json:"shop_status"`
	Valid      bool       `json:"valid"` // Valid is true if ShopStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShopStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive   SubscriptionStatus = "active"
	SubscriptionStatusPastDue  SubscriptionStatus = "past_due"
	SubscriptionStatusCanceled SubscriptionStatus = "canceled"
	SubscriptionStatusExpired  SubscriptionStatus = "expired"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type Album struct {
	ID           uuid.UUID          `json:"id"`
	ShopID       uuid.UUID          `json:"shop_id"`
	ParentID     uuid.NullUUID      `json:"parent_id"`
	Title        string             `json:"title"`
	CoverPhotoID uuid.NullUUID      `json:"cover_photo_id"`
	SortOrder    int32              `json:"sort_order"`
	IsHidden     bool               `json:"is_hidden"`
	PasswordHash *string            `json:"password_hash"`
	PhotoCount   int32              `json:"photo_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Complaint struct {
	ID         uuid.UUID          `json:"id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	PhotoID    uuid.NullUUID      `json:"photo_id"`
	Reason     string             `json:"reason"`
	Status     ComplaintStatus    `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type DailyStat struct {
	ShopID         uuid.UUID     `json:"shop_id"`
	Date           pgtype.Date   `json:"date"`
	AlbumID        uuid.NullUUID `json:"album_id"`
	Views          int64         `json:"views"`
	UniqueVisitors int64         `json:"unique_visitors"`
	LeadClicks     int64         `json:"lead_clicks"`
}

type LeadClick struct {
	ID          uuid.UUID          `json:"id"`
	ShopID      uuid.UUID          `json:"shop_id"`
	PhotoID     uuid.NullUUID      `json:"photo_id"`
	Channel     LeadChannel        `json:"channel"`
	VisitorHash string             `json:"visitor_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID          `json:"id"`
	ShopID            uuid.UUID          `json:"shop_id"`
	Plan              ShopPlan           `json:"plan"`
	Amount            int64              `json:"amount"`
	Currency          string             `json:"currency"`
	ProviderPaymentID *string            `json:"provider_payment_id"`
	Status            PaymentStatus      `json:"status"`
	Recurring         bool               `json:"recurring"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Photo struct {
	ID         uuid.UUID          `json:"id"`
	AlbumID    uuid.UUID          `json:"album_id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	Caption    string             `json:"caption"`
	CaptionTsv interface{}        `json:"caption_tsv"`
	Status     PhotoStatus        `json:"status"`
	OrigSize   int64              `json:"orig_size"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Phash      pgtype.Int8        `json:"phash"`
	Source     PhotoSource        `json:"source"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Shop struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	Contacts     []byte             `json:"contacts"`
	Settings     []byte             `json:"settings"`
	Status       ShopStatus         `json:"status"`
	Plan         ShopPlan           `json:"plan"`
	StorageUsed  int64              `json:"storage_used"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	BillingState BillingState       `json:"billing_state"`
	PaidUntil    pgtype.Timestamptz `json:"paid_until"`
}

type Subscription struct {
	ID              uuid.UUID          `json:"id"`
	ShopID          uuid.UUID          `json:"shop_id"`
	Plan            ShopPlan           `json:"plan"`
	Status          SubscriptionStatus `json:"status"`
	PeriodStart     pgtype.Timestamptz `json:"period_start"`
	PeriodEnd       pgtype.Timestamptz `json:"period_end"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PaymentMethodID *string            `json:"payment_method_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	TgUserID     pgtype.Int8        `json:"tg_user_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
