// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotosByAlbum = `-- name: CountPhotosByAlbum :one
SELECT count(*) FROM photos
WHERE album_id = $1 AND shop_id = $2
`

type CountPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
}

func (q *Queries) CountPhotosByAlbum(ctx context.Context, arg CountPhotosByAlbumParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosByAlbum, arg.AlbumID, arg.ShopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (album_id, shop_id, orig_size, source, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size
`

type CreatePhotoParams struct {
	AlbumID   uuid.UUID   `json:"album_id"`
	ShopID    uuid.UUID   `json:"shop_id"`
	OrigSize  int64       `json:"orig_size"`
	Source    PhotoSource `json:"source"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.AlbumID,
		arg.ShopID,
		arg.OrigSize,
		arg.Source,
		arg.SortOrder,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :execrows
DELETE FROM photos
WHERE id = $1 AND shop_id = $2
`

type DeletePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhoto, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleUploads = `-- name: DeleteStaleUploads :many
DELETE FROM photos
WHERE status = 'uploading'
  AND created_at < now() - make_interval(hours => $1::int)
RETURNING id, shop_id
`

type DeleteStaleUploadsRow struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Уборка зависших загрузок. Фото попадает в uploading при выдаче presign
// и выходит из него на confirm. Если confirm не дошёл — строка остаётся
// навсегда и продолжает занимать квоту (CountShopPhotos считает всё, кроме
// failed). На боевом стенде таких накопилось шесть штук за неделю.
func (q *Queries) DeleteStaleUploads(ctx context.Context, dollar_1 int32) ([]DeleteStaleUploadsRow, error) {
	rows, err := q.db.Query(ctx, deleteStaleUploads, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteStaleUploadsRow
	for rows.Next() {
		var i DeleteStaleUploadsRow
		if err := rows.Scan(&i.ID, &i.ShopID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failStaleProcessing = `-- name: FailStaleProcessing :many
UPDATE photos
SET status = 'failed', updated_at = now()
WHERE status = 'processing'
  AND updated_at < now() - make_interval(hours => $1::int)
RETURNING id
`

// Фото, застрявшее в processing: задача потерялась (сброс Redis) либо
// исчерпала ретраи и ушла в архив asynq — статус в БД при этом не меняется.
// Такое фото навсегда висит в кабинете со спиннером и занимает квоту.
// Оригинал в S3 не трогаем: поведение то же, что у обычного failed.
func (q *Queries) FailStaleProcessing(ctx context.Context, dollar_1 int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, failStaleProcessing, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size FROM photos
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
	)
	return i, err
}

const getPhotoForShop = `-- name: GetPhotoForShop :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size FROM photos
WHERE id = $1 AND shop_id = $2
`

type GetPhotoForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к фото только в связке с shop_id владельца.
func (q *Queries) GetPhotoForShop(ctx context.Context, arg GetPhotoForShopParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoForShop, arg.ID, arg.ShopID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
	)
	return i, err
}

const listAlbumTreePhotos = `-- name: ListAlbumTreePhotos :many
SELECT id, (orig_size + drv_size)::bigint AS bytes FROM photos
WHERE album_id = $1 OR album_id IN (SELECT id FROM albums WHERE parent_id = $1)
`

type ListAlbumTreePhotosRow struct {
	ID    uuid.UUID `json:"id"`
	Bytes int64     `json:"bytes"`
}

// Фото удаляемого альбома (вместе с подальбомами: parent_id — один уровень).
// Нужны и размеры для возврата квоты, и id для уборки объектов в S3:
// каскад по FK снесёт строки, но об S3 и storage_used он не знает.
func (q *Queries) ListAlbumTreePhotos(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTreePhotosRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTreePhotos, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTreePhotosRow
	for rows.Next() {
		var i ListAlbumTreePhotosRow
		if err := rows.Scan(&i.ID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size FROM photos
WHERE album_id = $1 AND shop_id = $2
ORDER BY sort_order, created_at
LIMIT $3 OFFSET $4
`

type ListPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

// Страницами: альбом на тарифе «Продавец» — до 5000 фото, и выдача целиком
// вешала кабинет на несколько секунд. У витрины пагинация была с самого
// начала, у кабинета её не было.
func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByAlbum,
		arg.AlbumID,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoFailed = `-- name: SetPhotoFailed :exec
UPDATE photos
SET status = 'failed', updated_at = now()
WHERE id = $1
`

func (q *Queries) SetPhotoFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPhotoFailed, id)
	return err
}

const setPhotoProcessing = `-- name: SetPhotoProcessing :one
UPDATE photos
SET status = 'processing', orig_size = $2, updated_at = now()
WHERE id = $1 AND status = 'uploading'
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size
`

type SetPhotoProcessingParams struct {
	ID       uuid.UUID `json:"id"`
	OrigSize int64     `json:"orig_size"`
}

// Переход uploading -> processing после подтверждения загрузки в S3.
func (q *Queries) SetPhotoProcessing(ctx context.Context, arg SetPhotoProcessingParams) (Photo, error) {
	row := q.db.QueryRow(ctx, setPhotoProcessing, arg.ID, arg.OrigSize)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
	)
	return i, err
}

const setPhotoReady = `-- name: SetPhotoReady :exec
UPDATE photos
SET status = 'ready', width = $2, height = $3, phash = $4, drv_size = $5, updated_at = now()
WHERE id = $1
`

type SetPhotoReadyParams struct {
	ID      uuid.UUID   `json:"id"`
	Width   int32       `json:"width"`
	Height  int32       `json:"height"`
	Phash   pgtype.Int8 `json:"phash"`
	DrvSize int64       `json:"drv_size"`
}

func (q *Queries) SetPhotoReady(ctx context.Context, arg SetPhotoReadyParams) error {
	_, err := q.db.Exec(ctx, setPhotoReady,
		arg.ID,
		arg.Width,
		arg.Height,
		arg.Phash,
		arg.DrvSize,
	)
	return err
}

const updatePhotoCaption = `-- name: UpdatePhotoCaption :one
UPDATE photos
SET caption = $3, updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size
`

type UpdatePhotoCaptionParams struct {
	ID      uuid.UUID `json:"id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Caption string    `json:"caption"`
}

func (q *Queries) UpdatePhotoCaption(ctx context.Context, arg UpdatePhotoCaptionParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhotoCaption, arg.ID, arg.ShopID, arg.Caption)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
	)
	return i, err
}
