// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPhotosByAlbum = `-- name: CountPhotosByAlbum :one
SELECT count(*) FROM photos
WHERE album_id = $1 AND shop_id = $2
`

type CountPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
}

func (q *Queries) CountPhotosByAlbum(ctx context.Context, arg CountPhotosByAlbumParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosByAlbum, arg.AlbumID, arg.ShopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (album_id, shop_id, orig_size, source, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged
`

type CreatePhotoParams struct {
	AlbumID   uuid.UUID   `json:"album_id"`
	ShopID    uuid.UUID   `json:"shop_id"`
	OrigSize  int64       `json:"orig_size"`
	Source    PhotoSource `json:"source"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.AlbumID,
		arg.ShopID,
		arg.OrigSize,
		arg.Source,
		arg.SortOrder,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :execrows
DELETE FROM photos
WHERE id = $1 AND shop_id = $2
`

type DeletePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhoto, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged FROM photos
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}

const getPhotoForShop = `-- name: GetPhotoForShop :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged FROM photos
WHERE id = $1 AND shop_id = $2
`

type GetPhotoForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к фото только в связке с shop_id владельца.
func (q *Queries) GetPhotoForShop(ctx context.Context, arg GetPhotoForShopParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoForShop, arg.ID, arg.ShopID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged FROM photos
WHERE album_id = $1 AND shop_id = $2
ORDER BY sort_order, created_at
LIMIT $3 OFFSET $4
`

type ListPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

// Страницами: альбом на тарифе «Продавец» — до 5000 фото, и выдача целиком
// вешала кабинет на несколько секунд. У витрины пагинация была с самого
// начала, у кабинета её не было.
func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByAlbum,
		arg.AlbumID,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoFailed = `-- name: SetPhotoFailed :exec
UPDATE photos
SET status = 'failed', updated_at = now()
WHERE id = $1
`

func (q *Queries) SetPhotoFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPhotoFailed, id)
	return err
}

const setPhotoProcessing = `-- name: SetPhotoProcessing :one
UPDATE photos
SET status = 'processing', orig_size = $2, updated_at = now()
WHERE id = $1 AND status = 'uploading'
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged
`

type SetPhotoProcessingParams struct {
	ID       uuid.UUID `json:"id"`
	OrigSize int64     `json:"orig_size"`
}

// Переход uploading -> processing после подтверждения загрузки в S3.
func (q *Queries) SetPhotoProcessing(ctx context.Context, arg SetPhotoProcessingParams) (Photo, error) {
	row := q.db.QueryRow(ctx, setPhotoProcessing, arg.ID, arg.OrigSize)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}

const setPhotoReady = `-- name: SetPhotoReady :exec
UPDATE photos
SET status = 'ready', width = $2, height = $3, phash = $4, updated_at = now()
WHERE id = $1
`

type SetPhotoReadyParams struct {
	ID     uuid.UUID   `json:"id"`
	Width  int32       `json:"width"`
	Height int32       `json:"height"`
	Phash  pgtype.Int8 `json:"phash"`
}

func (q *Queries) SetPhotoReady(ctx context.Context, arg SetPhotoReadyParams) error {
	_, err := q.db.Exec(ctx, setPhotoReady,
		arg.ID,
		arg.Width,
		arg.Height,
		arg.Phash,
	)
	return err
}

const updatePhotoCaption = `-- name: UpdatePhotoCaption :one
UPDATE photos
SET caption = $3, updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged
`

type UpdatePhotoCaptionParams struct {
	ID      uuid.UUID `json:"id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Caption string    `json:"caption"`
}

func (q *Queries) UpdatePhotoCaption(ctx context.Context, arg UpdatePhotoCaptionParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhotoCaption, arg.ID, arg.ShopID, arg.Caption)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
	)
	return i, err
}
