// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDeletedPhotos = `-- name: CountDeletedPhotos :one
SELECT count(*) FROM photos
WHERE shop_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CountDeletedPhotos(ctx context.Context, shopID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeletedPhotos, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhotosByAlbum = `-- name: CountPhotosByAlbum :one
SELECT count(*) FROM photos
WHERE album_id = $1 AND shop_id = $2 AND deleted_at IS NULL
`

type CountPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
}

func (q *Queries) CountPhotosByAlbum(ctx context.Context, arg CountPhotosByAlbumParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosByAlbum, arg.AlbumID, arg.ShopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (album_id, shop_id, orig_size, source, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at
`

type CreatePhotoParams struct {
	AlbumID   uuid.UUID   `json:"album_id"`
	ShopID    uuid.UUID   `json:"shop_id"`
	OrigSize  int64       `json:"orig_size"`
	Source    PhotoSource `json:"source"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.AlbumID,
		arg.ShopID,
		arg.OrigSize,
		arg.Source,
		arg.SortOrder,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :execrows
DELETE FROM photos
WHERE id = $1 AND shop_id = $2
`

type DeletePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeletePhoto(ctx context.Context, arg DeletePhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePhoto, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleUploads = `-- name: DeleteStaleUploads :many
DELETE FROM photos
WHERE status = 'uploading'
  AND created_at < now() - make_interval(hours => $1::int)
RETURNING id, shop_id
`

type DeleteStaleUploadsRow struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Уборка зависших загрузок. Фото попадает в uploading при выдаче presign
// и выходит из него на confirm. Если confirm не дошёл — строка остаётся
// навсегда и продолжает занимать квоту (CountShopPhotos считает всё, кроме
// failed). На боевом стенде таких накопилось шесть штук за неделю.
func (q *Queries) DeleteStaleUploads(ctx context.Context, dollar_1 int32) ([]DeleteStaleUploadsRow, error) {
	rows, err := q.db.Query(ctx, deleteStaleUploads, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteStaleUploadsRow
	for rows.Next() {
		var i DeleteStaleUploadsRow
		if err := rows.Scan(&i.ID, &i.ShopID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failStaleProcessing = `-- name: FailStaleProcessing :many
UPDATE photos
SET status = 'failed', fail_reason = 'lost', updated_at = now()
WHERE status = 'processing'
  AND updated_at < now() - make_interval(hours => $1::int)
RETURNING id
`

// Фото, застрявшее в processing: задача потерялась (сброс Redis) либо
// исчерпала ретраи и ушла в архив asynq — статус в БД при этом не меняется.
// Такое фото навсегда висит в кабинете со спиннером и занимает квоту.
// Оригинал в S3 не трогаем: поведение то же, что у обычного failed.
// Причина 'lost' отличает нашу поломку от негодного файла: остальные коды
// (unsupported_format, corrupt, too_large, empty) говорят продавцу, что не так
// с его файлом, а здесь с файлом всё в порядке — потерялась задача.
func (q *Queries) FailStaleProcessing(ctx context.Context, dollar_1 int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, failStaleProcessing, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at FROM photos
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}

const getPhotoForShop = `-- name: GetPhotoForShop :one
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at FROM photos
WHERE id = $1 AND shop_id = $2
`

type GetPhotoForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: доступ к фото только в связке с shop_id владельца.
func (q *Queries) GetPhotoForShop(ctx context.Context, arg GetPhotoForShopParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhotoForShop, arg.ID, arg.ShopID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}

const listAlbumTreePhotos = `-- name: ListAlbumTreePhotos :many
SELECT id, (orig_size + drv_size)::bigint AS bytes FROM photos
WHERE album_id = $1 OR album_id IN (SELECT id FROM albums WHERE parent_id = $1)
`

type ListAlbumTreePhotosRow struct {
	ID    uuid.UUID `json:"id"`
	Bytes int64     `json:"bytes"`
}

// Фото удаляемого альбома (вместе с подальбомами: parent_id — один уровень).
// Нужны и размеры для возврата квоты, и id для уборки объектов в S3:
// каскад по FK снесёт строки, но об S3 и storage_used он не знает.
func (q *Queries) ListAlbumTreePhotos(ctx context.Context, albumID uuid.UUID) ([]ListAlbumTreePhotosRow, error) {
	rows, err := q.db.Query(ctx, listAlbumTreePhotos, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTreePhotosRow
	for rows.Next() {
		var i ListAlbumTreePhotosRow
		if err := rows.Scan(&i.ID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedPhotos = `-- name: ListDeletedPhotos :many
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at FROM photos
WHERE shop_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id
LIMIT $2 OFFSET $3
`

type ListDeletedPhotosParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListDeletedPhotos(ctx context.Context, arg ListDeletedPhotosParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listDeletedPhotos, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
			&i.FailReason,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at FROM photos
WHERE album_id = $1 AND shop_id = $2 AND deleted_at IS NULL
ORDER BY sort_order, created_at, id
LIMIT $3 OFFSET $4
`

type ListPhotosByAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

// Страницами: альбом на тарифе «Продавец» — до 5000 фото, и выдача целиком
// вешала кабинет на несколько секунд. У витрины пагинация была с самого
// начала, у кабинета её не было.
// id в сортировке — не украшение: при одинаковых sort_order и created_at
// порядок между запросами не определён, и фото на границе страниц может
// задвоиться или пропасть. У публичной выборки это уже учтено.
func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByAlbum,
		arg.AlbumID,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
			&i.FailReason,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockShopForUpload = `-- name: LockShopForUpload :exec
SELECT pg_advisory_xact_lock(hashtext($1::text)::bigint)
`

// Счётчик фотографий проверяется и увеличивается под блокировкой на магазин:
// без неё параллельные presign читают одно и то же значение и все проходят.
// Блокировка транзакционная, снимается сама, и она на магазин — соседние
// продавцы друг друга не ждут.
func (q *Queries) LockShopForUpload(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockShopForUpload, dollar_1)
	return err
}

const nextAlbumSortOrder = `-- name: NextAlbumSortOrder :one
SELECT coalesce(max(sort_order), 0)::int + 1 FROM photos WHERE album_id = $1
`

// Следующее место в альбоме. Считается в той же транзакции, что и переход
// в processing, поэтому подтверждения одной пачки получают возрастающие
// номера в том порядке, в каком их перечислил клиент.
func (q *Queries) NextAlbumSortOrder(ctx context.Context, albumID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAlbumSortOrder, albumID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const purgeExpiredTrash = `-- name: PurgeExpiredTrash :many
DELETE FROM photos
WHERE deleted_at IS NOT NULL
  AND deleted_at < now() - make_interval(days => $1::int)
RETURNING id, shop_id, (orig_size + drv_size)::bigint AS bytes
`

type PurgeExpiredTrashRow struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
	Bytes  int64     `json:"bytes"`
}

// Ночная уборка: всё, что пролежало в корзине дольше срока хранения.
func (q *Queries) PurgeExpiredTrash(ctx context.Context, dollar_1 int32) ([]PurgeExpiredTrashRow, error) {
	rows, err := q.db.Query(ctx, purgeExpiredTrash, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurgeExpiredTrashRow
	for rows.Next() {
		var i PurgeExpiredTrashRow
		if err := rows.Scan(&i.ID, &i.ShopID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgePhoto = `-- name: PurgePhoto :one
DELETE FROM photos
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NOT NULL
RETURNING id, album_id, status, (orig_size + drv_size)::bigint AS bytes
`

type PurgePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

type PurgePhotoRow struct {
	ID      uuid.UUID   `json:"id"`
	AlbumID uuid.UUID   `json:"album_id"`
	Status  PhotoStatus `json:"status"`
	Bytes   int64       `json:"bytes"`
}

// Окончательное удаление одной фотографии из корзины.
func (q *Queries) PurgePhoto(ctx context.Context, arg PurgePhotoParams) (PurgePhotoRow, error) {
	row := q.db.QueryRow(ctx, purgePhoto, arg.ID, arg.ShopID)
	var i PurgePhotoRow
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Status,
		&i.Bytes,
	)
	return i, err
}

const purgeShopTrash = `-- name: PurgeShopTrash :many
DELETE FROM photos
WHERE shop_id = $1 AND deleted_at IS NOT NULL
RETURNING id, (orig_size + drv_size)::bigint AS bytes
`

type PurgeShopTrashRow struct {
	ID    uuid.UUID `json:"id"`
	Bytes int64     `json:"bytes"`
}

// Очистить корзину целиком: id и байты нужны для уборки S3 и возврата квоты.
func (q *Queries) PurgeShopTrash(ctx context.Context, shopID uuid.UUID) ([]PurgeShopTrashRow, error) {
	rows, err := q.db.Query(ctx, purgeShopTrash, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurgeShopTrashRow
	for rows.Next() {
		var i PurgeShopTrashRow
		if err := rows.Scan(&i.ID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPhotoDerivativeSize = `-- name: ResetPhotoDerivativeSize :exec
UPDATE photos SET drv_size = 0, updated_at = now() WHERE id = $1
`

// Деривативы удалены (блокировка модератором) — размер обнуляется вместе
// с возвратом байтов в квоту, иначе повторная обработка учтёт их дважды.
func (q *Queries) ResetPhotoDerivativeSize(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetPhotoDerivativeSize, id)
	return err
}

const restorePhoto = `-- name: RestorePhoto :one
UPDATE photos
SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NOT NULL
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at
`

type RestorePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Возврат из корзины. Альбом мог уехать вместе с удалением самого альбома —
// тогда каскад унёс и строку фотографии, и возвращать нечего.
func (q *Queries) RestorePhoto(ctx context.Context, arg RestorePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, restorePhoto, arg.ID, arg.ShopID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}

const setPhotoFailed = `-- name: SetPhotoFailed :exec
UPDATE photos
SET status = 'failed', fail_reason = $2, updated_at = now()
WHERE id = $1
`

type SetPhotoFailedParams struct {
	ID         uuid.UUID `json:"id"`
	FailReason string    `json:"fail_reason"`
}

func (q *Queries) SetPhotoFailed(ctx context.Context, arg SetPhotoFailedParams) error {
	_, err := q.db.Exec(ctx, setPhotoFailed, arg.ID, arg.FailReason)
	return err
}

const setPhotoProcessing = `-- name: SetPhotoProcessing :one
UPDATE photos
SET status = 'processing', orig_size = $2, sort_order = $3, updated_at = now()
WHERE id = $1 AND status = 'uploading'
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at
`

type SetPhotoProcessingParams struct {
	ID        uuid.UUID `json:"id"`
	OrigSize  int64     `json:"orig_size"`
	SortOrder int32     `json:"sort_order"`
}

// Переход uploading -> processing после подтверждения загрузки в S3.
// Здесь же фотография занимает место в альбоме: sort_order приходит
// из NextAlbumSortOrder. На presign он оставался нулём, и выдача падала
// на created_at — то есть на порядок, в котором до сервера доехали
// запросы параллельного загрузчика.
func (q *Queries) SetPhotoProcessing(ctx context.Context, arg SetPhotoProcessingParams) (Photo, error) {
	row := q.db.QueryRow(ctx, setPhotoProcessing, arg.ID, arg.OrigSize, arg.SortOrder)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}

const setPhotoReady = `-- name: SetPhotoReady :exec
UPDATE photos
SET status = 'ready', width = $2, height = $3, phash = $4, drv_size = $5, updated_at = now()
WHERE id = $1
`

type SetPhotoReadyParams struct {
	ID      uuid.UUID   `json:"id"`
	Width   int32       `json:"width"`
	Height  int32       `json:"height"`
	Phash   pgtype.Int8 `json:"phash"`
	DrvSize int64       `json:"drv_size"`
}

func (q *Queries) SetPhotoReady(ctx context.Context, arg SetPhotoReadyParams) error {
	_, err := q.db.Exec(ctx, setPhotoReady,
		arg.ID,
		arg.Width,
		arg.Height,
		arg.Phash,
		arg.DrvSize,
	)
	return err
}

const softDeletePhoto = `-- name: SoftDeletePhoto :execrows

UPDATE photos
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND shop_id = $2 AND deleted_at IS NULL
`

type SoftDeletePhotoParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// --- Корзина ---------------------------------------------------------------
// Удаление в два шага: сначала пометка, потом ночная уборка по сроку. Место
// в хранилище при пометке не возвращаем — объекты в S3 никуда не делись.
func (q *Queries) SoftDeletePhoto(ctx context.Context, arg SoftDeletePhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePhoto, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePhotoCaption = `-- name: UpdatePhotoCaption :one
UPDATE photos
SET caption = $3, updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason, deleted_at
`

type UpdatePhotoCaptionParams struct {
	ID      uuid.UUID `json:"id"`
	ShopID  uuid.UUID `json:"shop_id"`
	Caption string    `json:"caption"`
}

func (q *Queries) UpdatePhotoCaption(ctx context.Context, arg UpdatePhotoCaptionParams) (Photo, error) {
	row := q.db.QueryRow(ctx, updatePhotoCaption, arg.ID, arg.ShopID, arg.Caption)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ShopID,
		&i.Caption,
		&i.CaptionTsv,
		&i.Status,
		&i.OrigSize,
		&i.Width,
		&i.Height,
		&i.Phash,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flagged,
		&i.DrvSize,
		&i.FailReason,
		&i.DeletedAt,
	)
	return i, err
}
