// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicPhotos = `-- name: CountPublicPhotos :one
SELECT count(*) FROM photos
WHERE album_id = $1 AND status = 'ready'
`

func (q *Queries) CountPublicPhotos(ctx context.Context, albumID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicPhotos, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLeadClick = `-- name: CreateLeadClick :exec
INSERT INTO lead_clicks (shop_id, photo_id, channel, visitor_hash)
VALUES ($1, $2, $3, $4)
`

type CreateLeadClickParams struct {
	ShopID      uuid.UUID     `json:"shop_id"`
	PhotoID     uuid.NullUUID `json:"photo_id"`
	Channel     LeadChannel   `json:"channel"`
	VisitorHash string        `json:"visitor_hash"`
}

func (q *Queries) CreateLeadClick(ctx context.Context, arg CreateLeadClickParams) error {
	_, err := q.db.Exec(ctx, createLeadClick,
		arg.ShopID,
		arg.PhotoID,
		arg.Channel,
		arg.VisitorHash,
	)
	return err
}

const getActiveShopByID = `-- name: GetActiveShopByID :one
SELECT id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at FROM shops
WHERE id = $1 AND status = 'active' AND billing_state != 'suspended'
`

func (q *Queries) GetActiveShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getActiveShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}

const getPublicAlbum = `-- name: GetPublicAlbum :one
SELECT id, shop_id, parent_id, title, cover_photo_id, sort_order, password_hash, photo_count, created_at, updated_at, category_id, status, hidden_by_plan, description, blocked_by_moderator FROM albums
WHERE id = $1 AND shop_id = $2 AND status <> 'draft' AND NOT hidden_by_plan
  AND NOT blocked_by_moderator
`

type GetPublicAlbumParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetPublicAlbum(ctx context.Context, arg GetPublicAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, getPublicAlbum, arg.ID, arg.ShopID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ParentID,
		&i.Title,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.PasswordHash,
		&i.PhotoCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.Status,
		&i.HiddenByPlan,
		&i.Description,
		&i.BlockedByModerator,
	)
	return i, err
}

const listActiveShopSlugs = `-- name: ListActiveShopSlugs :many
SELECT slug, updated_at FROM shops
WHERE status = 'active' AND billing_state != 'suspended'
ORDER BY created_at
LIMIT 50000
`

type ListActiveShopSlugsRow struct {
	Slug      string             `json:"slug"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Для sitemap: slug и дата обновления активных магазинов.
func (q *Queries) ListActiveShopSlugs(ctx context.Context) ([]ListActiveShopSlugsRow, error) {
	rows, err := q.db.Query(ctx, listActiveShopSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveShopSlugsRow
	for rows.Next() {
		var i ListActiveShopSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFirstReadyPhotos = `-- name: ListFirstReadyPhotos :many
SELECT DISTINCT ON (album_id) album_id, id
FROM photos
WHERE shop_id = $1 AND status = 'ready'
ORDER BY album_id, sort_order, created_at
`

type ListFirstReadyPhotosRow struct {
	AlbumID uuid.UUID `json:"album_id"`
	ID      uuid.UUID `json:"id"`
}

// Фолбэк обложки: первое ready-фото каждого альбома магазина
// (merge с ListPublicAlbums — в handler).
func (q *Queries) ListFirstReadyPhotos(ctx context.Context, shopID uuid.UUID) ([]ListFirstReadyPhotosRow, error) {
	rows, err := q.db.Query(ctx, listFirstReadyPhotos, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFirstReadyPhotosRow
	for rows.Next() {
		var i ListFirstReadyPhotosRow
		if err := rows.Scan(&i.AlbumID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicAlbums = `-- name: ListPublicAlbums :many

SELECT a.id, a.parent_id, a.title, a.sort_order, a.photo_count,
       c.id AS cover_id
FROM albums a
LEFT JOIN photos c ON c.id = a.cover_photo_id AND c.status = 'ready'
WHERE a.shop_id = $1 AND a.status = 'published' AND NOT a.hidden_by_plan
  AND NOT a.blocked_by_moderator
  AND (a.photo_count > 0 OR EXISTS (
        SELECT 1 FROM albums ch
        WHERE ch.parent_id = a.id AND ch.status = 'published'
          AND NOT ch.hidden_by_plan AND NOT ch.blocked_by_moderator
          AND ch.photo_count > 0))
ORDER BY a.sort_order, a.created_at
LIMIT 1000
`

type ListPublicAlbumsRow struct {
	ID         uuid.UUID     `json:"id"`
	ParentID   uuid.NullUUID `json:"parent_id"`
	Title      string        `json:"title"`
	SortOrder  int32         `json:"sort_order"`
	PhotoCount int32         `json:"photo_count"`
	CoverID    uuid.NullUUID `json:"cover_id"`
}

// Публичное чтение витрины. Только активные магазины, не скрытые альбомы,
// фото в статусе ready. Приватные поля наружу не отдаются (см. handlers).
// Потолок здесь — страховка горячего пути: страница магазина отдаётся
// на каждый заход покупателя, и число альбомов в ней не должно зависеть
// от того, сколько их успел наделать продавец. Совпадает с потолком на
// создание альбомов, так что честный каталог не обрезается.
// Пустой альбом покупателю показывать незачем: тап по нему упирается
// в «здесь пока нет фото». Родителя, у которого фотографии лежат в
// подальбомах, при этом прятать нельзя — иначе исчезает целая ветка.
func (q *Queries) ListPublicAlbums(ctx context.Context, shopID uuid.UUID) ([]ListPublicAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listPublicAlbums, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicAlbumsRow
	for rows.Next() {
		var i ListPublicAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.SortOrder,
			&i.PhotoCount,
			&i.CoverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicChildAlbums = `-- name: ListPublicChildAlbums :many
SELECT a.id, a.parent_id, a.title, a.sort_order, a.photo_count,
       c.id AS cover_id
FROM albums a
LEFT JOIN photos c ON c.id = a.cover_photo_id AND c.status = 'ready'
WHERE a.parent_id = $1 AND a.status = 'published'
  AND NOT a.hidden_by_plan AND NOT a.blocked_by_moderator
  -- Глубже двух уровней альбомов не бывает, поэтому здесь достаточно
  -- собственного счётчика.
  AND a.photo_count > 0
ORDER BY a.sort_order, a.created_at, a.id
LIMIT 200
`

type ListPublicChildAlbumsRow struct {
	ID         uuid.UUID     `json:"id"`
	ParentID   uuid.NullUUID `json:"parent_id"`
	Title      string        `json:"title"`
	SortOrder  int32         `json:"sort_order"`
	PhotoCount int32         `json:"photo_count"`
	CoverID    uuid.NullUUID `json:"cover_id"`
}

// Подальбомы открытого альбома: покупатель приходит по прямой ссылке на
// родительскую категорию, и без них видит пустую страницу — вложенные
// альбомы показывались только на главной магазина.
func (q *Queries) ListPublicChildAlbums(ctx context.Context, parentID uuid.NullUUID) ([]ListPublicChildAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listPublicChildAlbums, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicChildAlbumsRow
	for rows.Next() {
		var i ListPublicChildAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.SortOrder,
			&i.PhotoCount,
			&i.CoverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPhotos = `-- name: ListPublicPhotos :many
SELECT id, album_id, shop_id, caption, caption_tsv, status, orig_size, width, height, phash, source, sort_order, created_at, updated_at, flagged, drv_size, fail_reason FROM photos
WHERE album_id = $1 AND status = 'ready'
ORDER BY sort_order, created_at, id
LIMIT $2 OFFSET $3
`

type ListPublicPhotosParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListPublicPhotos(ctx context.Context, arg ListPublicPhotosParams) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPublicPhotos, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
			&i.FailReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPhotosFTS = `-- name: SearchPhotosFTS :many
SELECT p.id, p.album_id, p.shop_id, p.caption, p.caption_tsv, p.status, p.orig_size, p.width, p.height, p.phash, p.source, p.sort_order, p.created_at, p.updated_at, p.flagged, p.drv_size, p.fail_reason,
       ts_rank(p.caption_tsv, websearch_to_tsquery('russian', $2)) AS rank
FROM photos p
JOIN albums a ON a.id = p.album_id
WHERE p.shop_id = $1
  AND p.status = 'ready'
  AND a.status = 'published'
  AND NOT a.hidden_by_plan
  AND NOT a.blocked_by_moderator
  AND p.caption_tsv @@ websearch_to_tsquery('russian', $2)
ORDER BY rank DESC, p.created_at DESC, p.id
LIMIT $3
`

type SearchPhotosFTSParams struct {
	ShopID             uuid.UUID `json:"shop_id"`
	WebsearchToTsquery string    `json:"websearch_to_tsquery"`
	Limit              int32     `json:"limit"`
}

type SearchPhotosFTSRow struct {
	ID         uuid.UUID          `json:"id"`
	AlbumID    uuid.UUID          `json:"album_id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	Caption    string             `json:"caption"`
	CaptionTsv interface{}        `json:"caption_tsv"`
	Status     PhotoStatus        `json:"status"`
	OrigSize   int64              `json:"orig_size"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Phash      pgtype.Int8        `json:"phash"`
	Source     PhotoSource        `json:"source"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Flagged    bool               `json:"flagged"`
	DrvSize    int64              `json:"drv_size"`
	FailReason string             `json:"fail_reason"`
	Rank       float32            `json:"rank"`
}

// Поиск по подписям: FTS с русской конфигурацией (основной путь).
func (q *Queries) SearchPhotosFTS(ctx context.Context, arg SearchPhotosFTSParams) ([]SearchPhotosFTSRow, error) {
	rows, err := q.db.Query(ctx, searchPhotosFTS, arg.ShopID, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPhotosFTSRow
	for rows.Next() {
		var i SearchPhotosFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
			&i.FailReason,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPhotosTrgm = `-- name: SearchPhotosTrgm :many
SELECT p.id, p.album_id, p.shop_id, p.caption, p.caption_tsv, p.status, p.orig_size, p.width, p.height, p.phash, p.source, p.sort_order, p.created_at, p.updated_at, p.flagged, p.drv_size, p.fail_reason,
       word_similarity($2, p.caption) AS sim
FROM photos p
JOIN albums a ON a.id = p.album_id
WHERE p.shop_id = $1
  AND p.status = 'ready'
  AND a.status = 'published'
  AND NOT a.hidden_by_plan
  AND NOT a.blocked_by_moderator
  AND word_similarity($2, p.caption) > 0.3
ORDER BY sim DESC, p.created_at DESC, p.id
LIMIT $3
`

type SearchPhotosTrgmParams struct {
	ShopID         uuid.UUID `json:"shop_id"`
	WordSimilarity string    `json:"word_similarity"`
	Limit          int32     `json:"limit"`
}

type SearchPhotosTrgmRow struct {
	ID         uuid.UUID          `json:"id"`
	AlbumID    uuid.UUID          `json:"album_id"`
	ShopID     uuid.UUID          `json:"shop_id"`
	Caption    string             `json:"caption"`
	CaptionTsv interface{}        `json:"caption_tsv"`
	Status     PhotoStatus        `json:"status"`
	OrigSize   int64              `json:"orig_size"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Phash      pgtype.Int8        `json:"phash"`
	Source     PhotoSource        `json:"source"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Flagged    bool               `json:"flagged"`
	DrvSize    int64              `json:"drv_size"`
	FailReason string             `json:"fail_reason"`
	Sim        float32            `json:"sim"`
}

// Fallback при пустом FTS-результате: pg_trgm по словам подписи
// (опечатки, частичные совпадения). Порог 0.3 подобран под кириллицу.
func (q *Queries) SearchPhotosTrgm(ctx context.Context, arg SearchPhotosTrgmParams) ([]SearchPhotosTrgmRow, error) {
	rows, err := q.db.Query(ctx, searchPhotosTrgm, arg.ShopID, arg.WordSimilarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPhotosTrgmRow
	for rows.Next() {
		var i SearchPhotosTrgmRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ShopID,
			&i.Caption,
			&i.CaptionTsv,
			&i.Status,
			&i.OrigSize,
			&i.Width,
			&i.Height,
			&i.Phash,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flagged,
			&i.DrvSize,
			&i.FailReason,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
