// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addShopStorageUsed = `-- name: AddShopStorageUsed :exec
UPDATE shops
SET storage_used = greatest(storage_used + $2, 0), updated_at = now()
WHERE id = $1
`

type AddShopStorageUsedParams struct {
	ID          uuid.UUID `json:"id"`
	StorageUsed int64     `json:"storage_used"`
}

func (q *Queries) AddShopStorageUsed(ctx context.Context, arg AddShopStorageUsedParams) error {
	_, err := q.db.Exec(ctx, addShopStorageUsed, arg.ID, arg.StorageUsed)
	return err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (owner_id, slug, name, description, contacts, settings)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at
`

type CreateShopParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Slug        string    `json:"slug"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Contacts    []byte    `json:"contacts"`
	Settings    []byte    `json:"settings"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.OwnerID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Contacts,
		arg.Settings,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}

const deleteShop = `-- name: DeleteShop :execrows
DELETE FROM shops
WHERE id = $1 AND owner_id = $2
`

type DeleteShopParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteShop(ctx context.Context, arg DeleteShopParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShop, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at FROM shops
WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}

const getShopForOwner = `-- name: GetShopForOwner :one
SELECT id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at FROM shops
WHERE id = $1 AND owner_id = $2
`

type GetShopForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

// Тенант-изоляция: доступ к магазину только владельцем.
func (q *Queries) GetShopForOwner(ctx context.Context, arg GetShopForOwnerParams) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopForOwner, arg.ID, arg.OwnerID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}

const listShopsByOwner = `-- name: ListShopsByOwner :many
SELECT id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at FROM shops
WHERE owner_id = $1
ORDER BY created_at
`

// Публичная витрина: только активные магазины; suspended по биллингу — скрыты.
func (q *Queries) ListShopsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Contacts,
			&i.Settings,
			&i.Status,
			&i.Plan,
			&i.StorageUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillingState,
			&i.PaidUntil,
			&i.SlugChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET name        = $3,
    description = $4,
    contacts    = $5,
    settings    = $6,
    updated_at  = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at
`

type UpdateShopParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Contacts    []byte    `json:"contacts"`
	Settings    []byte    `json:"settings"`
}

// Тенант-изоляция: обновление только владельцем (owner_id из сессии).
func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Contacts,
		arg.Settings,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}

const updateShopSlug = `-- name: UpdateShopSlug :one
UPDATE shops
SET slug = $3, slug_changed_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, name, description, contacts, settings, status, plan, storage_used, created_at, updated_at, billing_state, paid_until, slug_changed_at
`

type UpdateShopSlugParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
	Slug    string    `json:"slug"`
}

// Смена адреса — отдельным запросом: она ограничена по частоте и должна
// отмечать дату, а обычное сохранение настроек этого делать не должно.
func (q *Queries) UpdateShopSlug(ctx context.Context, arg UpdateShopSlugParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShopSlug, arg.ID, arg.OwnerID, arg.Slug)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Contacts,
		&i.Settings,
		&i.Status,
		&i.Plan,
		&i.StorageUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingState,
		&i.PaidUntil,
		&i.SlugChangedAt,
	)
	return i, err
}
