// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLeadClicksBetween = `-- name: CountLeadClicksBetween :many
SELECT shop_id, count(*) AS clicks
FROM lead_clicks
WHERE created_at >= $1 AND created_at < $2
GROUP BY shop_id
`

type CountLeadClicksBetweenParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type CountLeadClicksBetweenRow struct {
	ShopID uuid.UUID `json:"shop_id"`
	Clicks int64     `json:"clicks"`
}

func (q *Queries) CountLeadClicksBetween(ctx context.Context, arg CountLeadClicksBetweenParams) ([]CountLeadClicksBetweenRow, error) {
	rows, err := q.db.Query(ctx, countLeadClicksBetween, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLeadClicksBetweenRow
	for rows.Next() {
		var i CountLeadClicksBetweenRow
		if err := rows.Scan(&i.ShopID, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyStats = `-- name: UpsertDailyStats :exec

INSERT INTO daily_stats (shop_id, date, album_id, views, unique_visitors, lead_clicks)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (shop_id, date, album_id)
DO UPDATE SET views           = greatest(daily_stats.views, EXCLUDED.views),
              unique_visitors = greatest(daily_stats.unique_visitors, EXCLUDED.unique_visitors),
              lead_clicks     = EXCLUDED.lead_clicks
`

type UpsertDailyStatsParams struct {
	ShopID         uuid.UUID     `json:"shop_id"`
	Date           pgtype.Date   `json:"date"`
	AlbumID        uuid.NullUUID `json:"album_id"`
	Views          int64         `json:"views"`
	UniqueVisitors int64         `json:"unique_visitors"`
	LeadClicks     int64         `json:"lead_clicks"`
}

// Ночная агрегация просмотров из Redis и лидов из lead_clicks в daily_stats.
// Просмотры/уникальные приходят из Redis и после агрегации удаляются:
// GREATEST защищает от обнуления при повторном запуске за тот же день.
// Лиды пересчитываются из lead_clicks (PG) — обычная перезапись.
func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error {
	_, err := q.db.Exec(ctx, upsertDailyStats,
		arg.ShopID,
		arg.Date,
		arg.AlbumID,
		arg.Views,
		arg.UniqueVisitors,
		arg.LeadClicks,
	)
	return err
}
