// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tabs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAlbumToSection = `-- name: AddAlbumToSection :exec
INSERT INTO album_sections (album_id, section_id, sort_order)
SELECT a.id, $2, $3 FROM albums a
WHERE a.id = $1 AND a.shop_id = $4
ON CONFLICT (album_id, section_id) DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AddAlbumToSectionParams struct {
	ID        uuid.UUID `json:"id"`
	SectionID uuid.UUID `json:"section_id"`
	SortOrder int32     `json:"sort_order"`
	ShopID    uuid.UUID `json:"shop_id"`
}

// Альбом обязан принадлежать тому же магазину — иначе чужой альбом
// попал бы в чужую витрину.
func (q *Queries) AddAlbumToSection(ctx context.Context, arg AddAlbumToSectionParams) error {
	_, err := q.db.Exec(ctx, addAlbumToSection,
		arg.ID,
		arg.SectionID,
		arg.SortOrder,
		arg.ShopID,
	)
	return err
}

const clearSectionAlbums = `-- name: ClearSectionAlbums :exec
DELETE FROM album_sections WHERE section_id = $1
`

// Состав секции задаётся целиком: редактор всё равно сохраняет и порядок.
func (q *Queries) ClearSectionAlbums(ctx context.Context, sectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSectionAlbums, sectionID)
	return err
}

const createSection = `-- name: CreateSection :one
INSERT INTO sections (tab_id, title, sort_order)
VALUES ($1, $2, $3)
RETURNING id, tab_id, title, sort_order, created_at
`

type CreateSectionParams struct {
	TabID     uuid.UUID `json:"tab_id"`
	Title     string    `json:"title"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, createSection, arg.TabID, arg.Title, arg.SortOrder)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.TabID,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createTab = `-- name: CreateTab :one
INSERT INTO tabs (shop_id, title, slug, is_system, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, shop_id, title, slug, is_system, sort_order, created_at, updated_at
`

type CreateTabParams struct {
	ShopID    uuid.UUID `json:"shop_id"`
	Title     string    `json:"title"`
	Slug      string    `json:"slug"`
	IsSystem  bool      `json:"is_system"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateTab(ctx context.Context, arg CreateTabParams) (Tab, error) {
	row := q.db.QueryRow(ctx, createTab,
		arg.ShopID,
		arg.Title,
		arg.Slug,
		arg.IsSystem,
		arg.SortOrder,
	)
	var i Tab
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomTab = `-- name: DeleteCustomTab :execrows
DELETE FROM tabs
WHERE id = $1 AND shop_id = $2 AND is_system = false
`

type DeleteCustomTabParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Системные вкладки продавец не удаляет: they генерируются автоматически.
func (q *Queries) DeleteCustomTab(ctx context.Context, arg DeleteCustomTabParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomTab, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSection = `-- name: DeleteSection :execrows
DELETE FROM sections s
USING tabs t
WHERE s.tab_id = t.id AND s.id = $1 AND t.shop_id = $2
`

type DeleteSectionParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) DeleteSection(ctx context.Context, arg DeleteSectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSection, arg.ID, arg.ShopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSectionForShop = `-- name: GetSectionForShop :one
SELECT s.id, s.tab_id, s.title, s.sort_order, s.created_at FROM sections s
JOIN tabs t ON t.id = s.tab_id
WHERE s.id = $1 AND t.shop_id = $2
`

type GetSectionForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Секция проверяется через вкладку: собственного shop_id у неё нет.
func (q *Queries) GetSectionForShop(ctx context.Context, arg GetSectionForShopParams) (Section, error) {
	row := q.db.QueryRow(ctx, getSectionForShop, arg.ID, arg.ShopID)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.TabID,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getTabForShop = `-- name: GetTabForShop :one
SELECT id, shop_id, title, slug, is_system, sort_order, created_at, updated_at FROM tabs
WHERE id = $1 AND shop_id = $2
`

type GetTabForShopParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shop_id"`
}

// Тенант-изоляция: вкладка только в связке с shop_id владельца.
func (q *Queries) GetTabForShop(ctx context.Context, arg GetTabForShopParams) (Tab, error) {
	row := q.db.QueryRow(ctx, getTabForShop, arg.ID, arg.ShopID)
	var i Tab
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicSectionAlbums = `-- name: ListPublicSectionAlbums :many
SELECT s.id AS section_id, s.title AS section_title, s.sort_order AS section_order,
       a.id, a.shop_id, a.parent_id, a.title, a.cover_photo_id, a.sort_order, a.password_hash, a.photo_count, a.created_at, a.updated_at, a.category_id, a.status
FROM sections s
JOIN tabs t ON t.id = s.tab_id
LEFT JOIN album_sections asec ON asec.section_id = s.id
LEFT JOIN albums a ON a.id = asec.album_id AND a.status = 'published'
WHERE t.shop_id = $1 AND t.slug = $2
ORDER BY s.sort_order, s.created_at, asec.sort_order
`

type ListPublicSectionAlbumsParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Slug   string    `json:"slug"`
}

type ListPublicSectionAlbumsRow struct {
	SectionID    uuid.UUID          `json:"section_id"`
	SectionTitle string             `json:"section_title"`
	SectionOrder int32              `json:"section_order"`
	ID           uuid.NullUUID      `json:"id"`
	ShopID       uuid.NullUUID      `json:"shop_id"`
	ParentID     uuid.NullUUID      `json:"parent_id"`
	Title        *string            `json:"title"`
	CoverPhotoID uuid.NullUUID      `json:"cover_photo_id"`
	SortOrder    pgtype.Int4        `json:"sort_order"`
	PasswordHash *string            `json:"password_hash"`
	PhotoCount   pgtype.Int4        `json:"photo_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CategoryID   uuid.NullUUID      `json:"category_id"`
	Status       NullAlbumStatus    `json:"status"`
}

// Публичная выкладка: секции вкладки со своими альбомами, одним запросом.
// Скрытые альбомы не отдаются.
func (q *Queries) ListPublicSectionAlbums(ctx context.Context, arg ListPublicSectionAlbumsParams) ([]ListPublicSectionAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listPublicSectionAlbums, arg.ShopID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicSectionAlbumsRow
	for rows.Next() {
		var i ListPublicSectionAlbumsRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionTitle,
			&i.SectionOrder,
			&i.ID,
			&i.ShopID,
			&i.ParentID,
			&i.Title,
			&i.CoverPhotoID,
			&i.SortOrder,
			&i.PasswordHash,
			&i.PhotoCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionAlbumIDs = `-- name: ListSectionAlbumIDs :many
SELECT album_id FROM album_sections
WHERE section_id = $1
ORDER BY sort_order
`

func (q *Queries) ListSectionAlbumIDs(ctx context.Context, sectionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSectionAlbumIDs, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var album_id uuid.UUID
		if err := rows.Scan(&album_id); err != nil {
			return nil, err
		}
		items = append(items, album_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByShop = `-- name: ListSectionsByShop :many
SELECT s.id, s.tab_id, s.title, s.sort_order, s.created_at, t.slug AS tab_slug FROM sections s
JOIN tabs t ON t.id = s.tab_id
WHERE t.shop_id = $1
ORDER BY t.sort_order, s.sort_order, s.created_at
`

type ListSectionsByShopRow struct {
	ID        uuid.UUID          `json:"id"`
	TabID     uuid.UUID          `json:"tab_id"`
	Title     string             `json:"title"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TabSlug   string             `json:"tab_slug"`
}

func (q *Queries) ListSectionsByShop(ctx context.Context, shopID uuid.UUID) ([]ListSectionsByShopRow, error) {
	rows, err := q.db.Query(ctx, listSectionsByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionsByShopRow
	for rows.Next() {
		var i ListSectionsByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.TabID,
			&i.Title,
			&i.SortOrder,
			&i.CreatedAt,
			&i.TabSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTabsByShop = `-- name: ListTabsByShop :many
SELECT id, shop_id, title, slug, is_system, sort_order, created_at, updated_at FROM tabs
WHERE shop_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListTabsByShop(ctx context.Context, shopID uuid.UUID) ([]Tab, error) {
	rows, err := q.db.Query(ctx, listTabsByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tab
	for rows.Next() {
		var i Tab
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Title,
			&i.Slug,
			&i.IsSystem,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections s
SET title = $3, sort_order = $4
FROM tabs t
WHERE s.tab_id = t.id AND s.id = $1 AND t.shop_id = $2
RETURNING s.id, s.tab_id, s.title, s.sort_order, s.created_at
`

type UpdateSectionParams struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Title     string    `json:"title"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.ID,
		arg.ShopID,
		arg.Title,
		arg.SortOrder,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.TabID,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateTab = `-- name: UpdateTab :one
UPDATE tabs
SET title      = $3,
    sort_order = $4,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, title, slug, is_system, sort_order, created_at, updated_at
`

type UpdateTabParams struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shop_id"`
	Title     string    `json:"title"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateTab(ctx context.Context, arg UpdateTabParams) (Tab, error) {
	row := q.db.QueryRow(ctx, updateTab,
		arg.ID,
		arg.ShopID,
		arg.Title,
		arg.SortOrder,
	)
	var i Tab
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Title,
		&i.Slug,
		&i.IsSystem,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
